webtalk_init -webtalk_dir /media/engin/StorageA/FPGA/pipelined/pipelined.sim/sim_1/behav/xsim/xsim.dir/pipetop_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Jun 16 09:42:14 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3118627" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "e0cbefba-9aa5-4d71-9098-794189fdf858" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "ee2a9eb60d0a4c87bf866307354037f4" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "239" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 20.04.2 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 3800X 8-Core Processor" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1886.034 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "33.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "528745 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "3.87_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "116908_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3823114515 -regid "" -xml /media/engin/StorageA/FPGA/pipelined/pipelined.sim/sim_1/behav/xsim/xsim.dir/pipetop_behav/webtalk/usage_statistics_ext_xsim.xml -html /media/engin/StorageA/FPGA/pipelined/pipelined.sim/sim_1/behav/xsim/xsim.dir/pipetop_behav/webtalk/usage_statistics_ext_xsim.html -wdm /media/engin/StorageA/FPGA/pipelined/pipelined.sim/sim_1/behav/xsim/xsim.dir/pipetop_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
