# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /media/engin/StorageA/FPGA/pipelined/pipelined.srcs/sources_1/ip/uartfifo/uartfifo.xci
# IP: The module: 'uartfifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/engin/StorageA/FPGA/pipelined/pipelined.gen/sources_1/ip/uartfifo/uartfifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'uartfifo'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /media/engin/StorageA/FPGA/pipelined/pipelined.gen/sources_1/ip/uartfifo/uartfifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'uartfifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /media/engin/StorageA/FPGA/pipelined/pipelined.gen/sources_1/ip/uartfifo/uartfifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'uartfifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /media/engin/StorageA/FPGA/pipelined/pipelined.srcs/sources_1/ip/uartfifo/uartfifo.xci
# IP: The module: 'uartfifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/engin/StorageA/FPGA/pipelined/pipelined.gen/sources_1/ip/uartfifo/uartfifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'uartfifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /media/engin/StorageA/FPGA/pipelined/pipelined.gen/sources_1/ip/uartfifo/uartfifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'uartfifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /media/engin/StorageA/FPGA/pipelined/pipelined.gen/sources_1/ip/uartfifo/uartfifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'uartfifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
