# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/a7100t.xdc

# IP: ip/iram/iram.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==iram || ORIG_REF_NAME==iram} -quiet] -quiet

# IP: ip/masterclock/masterclock.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==masterclock || ORIG_REF_NAME==masterclock} -quiet] -quiet

# XDC: /media/engin/StorageA/FPGA/pipelined/pipelined.gen/sources_1/ip/iram/iram_ooc.xdc
